### ISSUE TITLE
caffe-extract-features: not found

### ISSUE THREAD

**Issue by Bazian** [fabiocarrara/pyffe#1]
In the function extract_features(), before returning lmdb_name, you execute 'caffe-extract-features' on the shell with some arguments. But I can't find any such command line option for caffe and it returns a 'not found' error.

**Comment by fabiocarrara** [comment]
My bad, it is a custom symlink to the extract_features caffe binary that I used in my configuration.
I replaced it with the default path for an /opt installation of caffe (/opt/caffe/build/tools/extract_features).
